name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  SONARQUBE_URL: 'http://34.125.125.40:9000'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GCLOUD_PROJECT: 'charged-gravity-425405-j6'
  IMAGE_NAME: 'java-application'
  DOCKER_REPO: 'asia-east1-docker.pkg.dev/charged-gravity-425405-j6/docker-image'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{ secrets.GCP_CREDS }}

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: SonarQube Analysis
        run: mvn clean verify sonar:sonar \
          -Dsonar.projectKey=rajat-github \
          -Dsonar.host.url=$SONARQUBE_URL \
          -Dsonar.login=$SONAR_TOKEN
