name: CI/CD Pipeline

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.7

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.2
      with:
        credentials_json: ${{ secrets.GCP_CREDS }}

    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'maven'

   
    
        
    

    
  

